#cloud-config
#update all packages
package_upgrade: true

#set up users
users:
  - name: klaus
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO1QYZfvmPFlaxFVaOeSsGo4RgK+Yl7coaC8pb9xk/Vk klaus@macairlet.agnoletti.net

#edit sshd_config and restart sshd
runcmd:
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config #Make sure ssh root login is disabled
  - sed -i -e '/^PasswordAuthentication/s/^.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config #we want ssh to accept passwd so we can bruteforce it for testing crowdsec
  - sed -i -e '/^PermitEmptyPasswords/s/^.*$/PermitEmptyPasswords no' /etc/ssh/sshd_config #wants to make sure that login with empty passwords is not possiible
  - restart ssh