#cloud-config
#update all packages
package_upgrade: true

#set up users
users:
  - name: klaus
    ssh-authorized-keys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO1QYZfvmPFlaxFVaOeSsGo4RgK+Yl7coaC8pb9xk/Vk klaus@macairlet.agnoletti.net
sudo: ['ALL=(ALL) NOPASSWD:ALL']
groups: sudo
shell: /bin/bash
passwd: $6$zCn6OiUZPvRwVFk0$KiYocLD7.glmCJ6Fz24EhPjDC8fRRMzHeE0pxDCI2nL7Ip2MqhegpO0zpYE46F9jfO0HbBBm1ywnH1ti3iLKE/:18410:0:99999:7

#edit sshd_config and restart sshd
runcmd:
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config #Make sure ssh root login is disabled
  - sed -i -e '/^PasswordAuthentication/s/^.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config #we want ssh to accept passwd so we can bruteforce it for testing crowdsec
  - restart ssh